name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build    

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo NODE_VERSION=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node_version: ${{ env.NODE_VERSION }}

      - name: run Build
        run: |
          npm install
          npm run build
