name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node_version }}

      - name: run Lint
        run: |
          npm install
          npm run lint
